#! /bin/bash

bspc config focused_border_color "#de935f"
bspc config normal_border_color "#8abeb7"
bspc config window_gap 8
bspc config border_width 2
bspc monitor HDMI-1-1 --remove
#bspc monitor --reset-desktops Terminal Code Browser Configs Media Social
#bspc monitor --reset-desktops Browse Edit Run 1 2 3
bspc monitor --reset-desktops Browser Code Run LaTeX Terminals Spotify Discord Misc

bspc rule --add NetLogo state=floating
bspc rule --add NetLogo3D state=floating
bspc rule --add Zathura state=tiled
