#! /bin/bash

bspc config focused_border_color "#de935f"
bspc config normal_border_color "#c5c8c6"
bspc config window_gap 48
bspc config border_width 2
bspc monitor HDMI-1-1 --remove
bspc monitor --reset-desktops Terminal Code Browser Configs Media Social

bspc rule --add NetLogo state=floating
bspc rule --add NetLogo3D state=floating
bspc rule --add Zathura state=tiled
